// packages/react/src/components/avatar/avatar-image.tsx
import React from 'react'
import { useAvatarContext } from './use-avatar-context'
import { useImageLoadingStatus } from '@pkmer-ui/react/hooks/useImageLoadingStatus'

interface AvatarImageProps extends React.ComponentPropsWithRef<'img'> {}

const AvatarImage: React.FC<AvatarImageProps> = props => {
  const { ref, src, alt, ...imgProps } = props
  const imgStatus = useImageLoadingStatus(src)
  const context = useAvatarContext()
  // todo ref callback
  React.useLayoutEffect(() => {
    if (imgStatus !== 'idle') {
      context.onImageLoadingStatusChange(imgStatus)
    }
  }, [imgStatus])

  return <>{imgStatus === 'loaded' ? <img ref={ref} src={src} alt={alt} {...imgProps} /> : null}</>
}

export { AvatarImage, type AvatarImageProps }

// packages/vue/src/components/avatar/AvatarImage.vue
<script lang="ts">
interface AvatarImageProps {
  src: string
  alt?: string
}
</script>
<script setup lang="ts">
import { inject, watch } from 'vue'
import { avatarContextKey } from './constants'
import { useImageLoadingStatus } from './useImageLoadingStatus'
const props = defineProps<AvatarImageProps>()
const context = inject(avatarContextKey)!
const state = useImageLoadingStatus(props.src)

watch(
  () => state.value,
  newVal => {
    if (newVal !== 'idle') context.onImageLoadingStatusChange(newVal)
  },
  {
    immediate: true
  }
)
</script>
<template>
  <img v-if="context.imageLoadingStatus.value === 'loaded'" v-bind="props" />
</template>
